import { IsIn, IsString, Length, Matches } from "class-validator";

/**
 * Body for POST /api/push/live-activity — Sprint E.5.
 *
 * The mobile app calls `ActivityKit.Activity.start()` which returns:
 *   - `activityID`: a UUID generated by iOS (we pass it as `activityId`)
 *   - `pushTokenUpdates`: an async stream of APNs push tokens (32–64 hex
 *     chars) that the server uses to push updates.
 *
 * The mobile app POSTs this DTO with the FIRST token received, plus the
 * activity kind (so the worker knows which contentState schema applies)
 * and the app's bundleId (so the worker can construct the APNs topic).
 *
 * Subsequent token rotations from the same activity ARE expected — iOS may
 * rotate the push token. The mobile app POSTs the same `activityId` with
 * the new `pushToken` and the server upserts.
 *
 * Privacy: this endpoint does NOT accept any contentState. Updates flow
 * through a separate `PATCH /api/push/live-activity/:activityId` once we
 * have backend integrations that need it.
 */
export class RegisterLiveActivityDto {
  @IsString()
  @Length(8, 64)
  activityId!: string;

  @IsIn(["TERAPIA_SESSION", "LECTOR_ACTIVE", "ECO_ACTIVE"])
  kind!: "TERAPIA_SESSION" | "LECTOR_ACTIVE" | "ECO_ACTIVE";

  @IsString()
  // APNs push tokens for Live Activities are hex strings, typically 64
  // chars. We allow 32–256 to be defensive against format changes.
  @Length(32, 256)
  @Matches(/^[0-9a-fA-F]+$/, {
    message: "pushToken must be a hex string",
  })
  pushToken!: string;

  @IsString()
  // Bundle ID format: reverse-DNS. Example: "com.psico.platform". We don't
  // hard-validate the format (apps can pick any) but cap the length.
  @Length(3, 128)
  bundleId!: string;
}
