[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@10.33.2", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo run build --filter=@psico/api"]

[start]
cmd = "pnpm --filter @psico/api start:prod"
