/**
 * EEC-C02's five guided readings, as the route OFFERS them.
 *
 * GENERATED by `node scripts/eec/build-discovery-entries.mjs`. Its five
 * Experiences have been PUBLISHED since September 2026; only the offer was
 * missing.
 *
 * Provenance differs from C03–C10 on purpose. C02's manifests predate the
 * `title` field, so the titles and durations come from the approved web
 * bundle — the table the reader already sees — and only the descriptions come
 * from the manifests' own INTRO paragraph. Nothing here is new copy.
 */

import type { GuideDiscoveryEntry } from "./guide-discovery-catalog";

export const EEC_C02_DISCOVERY_ENTRIES: readonly GuideDiscoveryEntry[] = [
  {
    bookSlug: "emociones-en-construccion",
    chapterOrder: 2,
    order: 1,
    pin: {
      guideKey: "eec-c2-universal-no-significa-uniforme",
      guideVersion: 1,
    },
    title: "Lo universal no significa uniforme",
    description:
      "«¿Las emociones son universales?» parece una sola pregunta, y en realidad son varias. Vas a separar seis niveles que el capítulo distingue y a ver qué permite concluir cada uno.",
    estimatedMinutes: "8–10",
  },
  {
    bookSlug: "emociones-en-construccion",
    chapterOrder: 2,
    order: 2,
    pin: { guideKey: "eec-c2-cultura-gramatica-no-destino", guideVersion: 1 },
    title: "La cultura es gramática, no destino",
    description:
      "La cultura enseña qué suele notarse, qué puede decirse y qué respuesta se espera. Vas a tomar una generalización rígida y a convertirla en algo más preciso: una tendencia, un contexto, una persona concreta y lo que falta saber.",
    estimatedMinutes: "9–11",
  },
  {
    bookSlug: "emociones-en-construccion",
    chapterOrder: 2,
    order: 3,
    pin: { guideKey: "eec-c2-gesto-necesita-contexto", guideVersion: 1 },
    title: "Un gesto necesita contexto",
    description:
      "Un gesto visible casi siempre admite más de una lectura. Vas a practicar un recorrido corto: describir lo que se observa, sostener dos interpretaciones posibles, notar qué contexto falta y elegir una pregunta para comprobar.",
    estimatedMinutes: "8–10",
  },
  {
    bookSlug: "emociones-en-construccion",
    chapterOrder: 2,
    order: 4,
    pin: { guideKey: "eec-c2-palabras-dan-contorno", guideVersion: 1 },
    title: "Las palabras dan contorno",
    description:
      "«Pena», «coraje», «sentido», «nervioso»: la misma palabra puede señalar experiencias distintas según la región, la familia y la escena. Vas a comparar cuatro frases en dos contextos y a notar qué información ayuda a interpretarlas.",
    estimatedMinutes: "8–10",
  },
  {
    bookSlug: "emociones-en-construccion",
    chapterOrder: 2,
    order: 5,
    pin: { guideKey: "eec-c2-rituales-dan-marco-no-guion", guideVersion: 1 },
    title: "Los rituales dan marco, no guion",
    description:
      "Un ritual puede organizar el tiempo, reunir testigos y ofrecer palabras cuando cuesta ordenar lo que pasa. Vas a practicar cómo acompañar sin prescribir: convertir un «deberías» en una opción o en una pregunta.",
    estimatedMinutes: "9–11",
  },
];
