import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { EXERCISE_INGESTION_CATALOG } from "./exercise-ingestion-catalog";

/**
 * The bridge between the server-side recall catalog and the web tables.
 *
 * The catalog is TypeScript compiled by the API, and the web microguide tables
 * are generated by a plain Node script (`scripts/eec/build-web-microguides.mjs`)
 * that cannot import it. This spec is what carries the PUBLIC half across: it
 * emits `artifacts/eec/guides-recall-public.json` — question plus the three
 * option labels — and nothing else.
 *
 * It is a spec rather than a build step because the invariant matters more than
 * the file: `correctOptionKey` must never cross this line. Emitting it here
 * would put it in a committed artifact, from there into a web table, and from
 * there into the DOM. The assertion below is the thing standing in the way, and
 * it runs on every `pnpm test`.
 */

const ROOT = join(__dirname, "..", "..", "..", "..");
const OUT = join(ROOT, "artifacts/eec/guides-recall-public.json");

describe("EEC · the recall catalog's public half", () => {
  it("emits question + options, and never the answer", () => {
    const pairs = EXERCISE_INGESTION_CATALOG["emociones-en-construccion"] ?? [];
    const publicHalf: Record<
      string,
      { question: string; options: { optionKey: string; label: string }[] }
    > = {};
    for (const pair of pairs) {
      publicHalf[pair.recall.exerciseKey] = {
        question: pair.recall.title,
        // `key` is renamed to `optionKey` because that is what the web bundle
        // calls it; the VALUE is the same, so a click still names the option
        // the ledger grades.
        options: pair.recall.content.options.map((o) => ({
          optionKey: o.key,
          label: o.label,
        })),
      };
    }

    const serialised = `${JSON.stringify(publicHalf, null, 2)}\n`;

    // The whole reason this file exists.
    expect(serialised).not.toContain("correctOptionKey");
    for (const pair of pairs) {
      expect(serialised).not.toContain(
        `"${pair.recall.content.correctOptionKey}":`,
      );
    }
    // Every recall carries exactly three options and no grading field.
    for (const entry of Object.values(publicHalf)) {
      expect(entry.options).toHaveLength(3);
      for (const o of entry.options) {
        expect(Object.keys(o).sort()).toEqual(["label", "optionKey"]);
      }
    }

    writeFileSync(OUT, serialised);
    // Committed, so the generator can run without the API build. If this fails
    // the artifact drifted from the catalog and the web tables are stale.
    expect(readFileSync(OUT, "utf8")).toBe(serialised);
  });
});
