/**
 * PQP-C06's 3 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C06` from
 * `scripts/pqp/chapters/c06.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C06: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 7 — unit 1 is the front matter.
  keyPrefix: "pqp-c6",
  chapterLabel: "capítulo 6",
};

export const PQP_C06_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "senales-de-crisis",
    practiceSlug: "una-senal-en-dos-momentos",
    title: "Las señales tempranas",
    summary:
      "No todas las crisis llegan de golpe. El capítulo describe las que se instalan sin ruido, y por qué cuesta tanto verlas a tiempo.",
    duration: "8–10 minutos",
    intro: {
      title: "Las señales tempranas",
      body: [
        "No todas las crisis llegan de golpe. El capítulo describe las que se instalan sin ruido, y por qué cuesta tanto verlas a tiempo.",
      ],
      note: "Trabajaremos con una escena inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Detectar las señales de una crisis",
      body: "Lee la sección donde el capítulo enumera señales tempranas, y fíjate en cuáles no parecen graves vistas de una en una.",
    },
    concept: {
      title: "Lo que se normaliza deja de verse",
      body: [
        "Muchas de las señales que describe el capítulo son discretas: menos conversación de la que había, menos gestos de afecto, planes que dejan de compartirse, una sensación difusa de que algo falta.",
        "Cada una por separado puede no significar nada. Lo que las vuelve significativas es que se sostengan y que nadie las nombre, porque a lo que dura mucho tiempo se le deja de prestar atención.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa tu relación ni concluye nada sobre ella. Reconocer una señal en una lista no es un diagnóstico.",
    },
    practice: {
      title: "Una señal en dos momentos",
      body: [
        "Las mismas señales de una pareja inventada, en dos situaciones distintas. Observa qué haría falta saber para interpretarlas.",
      ],
      note: "Es un caso editorial, no tu relación. Nada se marca como correcto: el ejercicio es notar qué información falta.",
    },
    recall: {
      question:
        "Según el capítulo, ¿cómo se manifiestan muchas crisis de pareja?",
      options: [
        {
          optionKey: "pqp-c6-opcion-instalan-despacio",
          label:
            "Se instalan despacio, con señales discretas que se normalizan antes de que nadie las nombre.",
        },
        {
          optionKey: "pqp-c6-opcion-siempre-estallan",
          label:
            "Estallan siempre en un episodio claro que ambos identifican en el momento.",
        },
        {
          optionKey: "pqp-c6-opcion-solo-graves",
          label:
            "Solo aparecen cuando ocurre algo grave, como una pérdida o una infidelidad.",
        },
      ],
    },
    summaryScene: {
      title: "Nombrarlo antes",
      body: [
        "Las señales que describe el capítulo casi nunca son dramáticas. Lo que las vuelve importantes es que duren y que nadie las diga en voz alta.",
      ],
    },
  },
  {
    slug: "pedir-ayuda-no-es-debilidad",
    practiceSlug: "de-la-idea-a-la-consulta",
    title: "Pedir ayuda no es debilidad",
    summary:
      "Muchas parejas llegan a terapia tarde, y no por falta de dificultades. El capítulo se detiene en por qué.",
    duration: "8–10 minutos",
    intro: {
      title: "Pedir ayuda no es debilidad",
      body: [
        "Muchas parejas llegan a terapia tarde, y no por falta de dificultades. El capítulo se detiene en por qué.",
      ],
      note: "Trabajaremos con un caso inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Buscar ayuda no es debilidad, es sabiduría",
      body: "Lee la sección sobre la ayuda externa y fíjate en cómo la sitúa el capítulo: no como un último recurso.",
    },
    concept: {
      title: "Antes, no cuando ya no queda nada",
      body: [
        "El capítulo sostiene que hay dificultades que no se resuelven solo entre dos, y que buscar acompañamiento es una decisión razonable y no la señal de que algo fracasó.",
        "Situarla como último recurso tiene un coste concreto: se llega con más desgaste acumulado y con menos margen para trabajar.",
      ],
      note: "Si algo de lo que lees te resuena, pedir ayuda es una opción disponible ahora, no dentro de un tiempo. Marcar la escena no evalúa tu situación ni saca conclusiones sobre ella.",
    },
    practice: {
      title: "De la idea a la consulta",
      body: [
        "Ordena los pasos de un caso inventado, desde que alguien piensa que quizá les vendría bien hasta que ocurre.",
      ],
      note: "Es un caso editorial, no tu historia.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué lugar tiene la ayuda externa en una crisis de pareja?",
      options: [
        {
          optionKey: "pqp-c6-opcion-hay-crisis-que-la-necesitan",
          label:
            "Hay crisis que necesitan intervención externa, y buscarla es una decisión sensata y no una derrota.",
        },
        {
          optionKey: "pqp-c6-opcion-ultimo-recurso",
          label:
            "Conviene reservarla como último recurso, cuando ya se han agotado los intentos entre los dos.",
        },
        {
          optionKey: "pqp-c6-opcion-solo-si-ambos",
          label:
            "Solo tiene sentido si ambos están igual de convencidos desde el principio.",
        },
      ],
    },
    summaryScene: {
      title: "Una opción, no una rendición",
      body: [
        "Buscar ayuda es una decisión disponible en cualquier momento, y llegar antes suele dejar más margen que llegar al final.",
      ],
    },
  },
  {
    slug: "crecimiento-posible-no-obligatorio",
    practiceSlug: "que-dejo-esta-crisis",
    title: "A veces se aprende, y a veces se pierde",
    summary:
      "El capítulo cuenta cómo una crisis puede dejar algo valioso. Esta guía se detiene también en lo que eso no significa.",
    duration: "8–10 minutos",
    intro: {
      title: "A veces se aprende, y a veces se pierde",
      body: [
        "El capítulo cuenta cómo una crisis puede dejar algo valioso. Esta guía se detiene también en lo que eso no significa.",
      ],
      note: "Puede tocar recuerdos difíciles; todas las preguntas son opcionales. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "La crisis como umbral de crecimiento",
      body: "Lee la sección final, donde el autor describe lo que una dificultad dejó en su propia historia.",
    },
    concept: {
      title: "Posible, no obligatorio",
      body: [
        "El capítulo describe que una pareja que atraviesa una crisis con apertura y trabajo puede salir de ella con algo que antes no tenía. Es una posibilidad real, y vale la pena conocerla.",
        "Conviene decir con la misma claridad lo que no se sigue de ahí. Hay crisis que dejan aprendizaje, otras que dejan pérdida, y otras que siguen abiertas mucho tiempo. Ninguna de esas salidas dice nada sobre lo que valen las personas que la atraviesan, y nadie está obligado a encontrarle un sentido a lo que le dolió.",
      ],
      note: "Esta precisión es de FeelVerse: una crisis no ocurre para enseñar nada, y no crecer no es un fallo. Marcar la escena no evalúa tu situación.",
    },
    practice: {
      title: "¿Qué dejó esta crisis?",
      body: [
        "Cuatro desenlaces inventados de cuatro parejas distintas. Distingue lo que cada escena muestra de lo que estaríamos suponiendo.",
      ],
      note: "Son casos editoriales. Ninguno es un modelo a seguir ni un pronóstico: incluyen desenlaces en los que nada mejoró, porque también ocurren.",
    },
    recall: {
      question:
        "Según la idea trabajada en esta guía, ¿qué se puede decir del aprendizaje después de una crisis?",
      options: [
        {
          optionKey: "pqp-c6-opcion-puede-ocurrir",
          label:
            "Que puede ocurrir cuando hay apertura y trabajo, pero no está garantizado ni es obligatorio.",
        },
        {
          optionKey: "pqp-c6-opcion-toda-crisis-fortalece",
          label:
            "Que toda crisis fortalece a la pareja que la atraviesa unida.",
        },
        {
          optionKey: "pqp-c6-opcion-sucede-por-algo",
          label:
            "Que las crisis ocurren para enseñar algo que la pareja necesitaba aprender.",
        },
      ],
    },
    summaryScene: {
      title: "Sin deberes",
      body: [
        "Una crisis puede dejar aprendizaje. No tiene que hacerlo, y no haberlo encontrado no es una tarea pendiente.",
      ],
    },
  },
];

export const PQP_C06_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C06_MICROGUIDES.map((m) => microguidePresentation(PQP_C06, m));

export const PQP_C06_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C06_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C06, m));
