/**
 * PQP-C08's 5 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C08` from
 * `scripts/pqp/chapters/c08.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C08: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 9 — unit 1 is the front matter.
  keyPrefix: "pqp-c8",
  chapterLabel: "capítulo 8",
};

export const PQP_C08_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "cinco-lenguajes-como-mapa",
    practiceSlug: "que-idioma-habla-cada-gesto",
    title: "Un mapa de preferencias, no una etiqueta",
    summary:
      "Palabras, tiempo, detalles, actos y contacto. El capítulo los usa como mapa; esta guía se detiene en para qué sirve un mapa y para qué no.",
    duration: "8–10 minutos",
    intro: {
      title: "Un mapa de preferencias, no una etiqueta",
      body: [
        "Palabras, tiempo, detalles, actos y contacto. El capítulo los usa como mapa; esta guía se detiene en para qué sirve un mapa y para qué no.",
      ],
      note: "Trabajaremos con gestos inventados para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Los cinco lenguajes del amor",
      body: "Lee la sección donde el capítulo describe los cinco, con los ejemplos que da de cada uno.",
    },
    concept: {
      title: "Cinco formas, no cinco tipos de persona",
      body: [
        "El capítulo recoge la propuesta de Gary Chapman: cinco formas principales en que las personas dan y reciben amor —palabras de afirmación, tiempo de calidad, detalles y regalos, actos de servicio y contacto físico.",
        "Conviene decir qué clase de herramienta es. Es un marco divulgativo sobre preferencias, muy útil para nombrar lo que a cada quien le llega, y no una clasificación validada ni un diagnóstico. Nadie «es» un lenguaje: las preferencias conviven, cambian con el tiempo y no encasillan a nadie.",
      ],
      note: "Marcar esta escena registra que exploraste la idea. No te asigna un lenguaje, no clasifica a nadie y no mide compatibilidad.",
    },
    practice: {
      title: "¿Qué idioma habla cada gesto?",
      body: [
        "Cinco gestos inventados. Reconoce cuál de los cinco lenguajes habla cada uno.",
      ],
      note: "Se clasifican gestos, no personas. No hay respuesta correcta ni puntaje: un mismo gesto puede hablar más de un idioma, y eso también es información.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué describen los cinco lenguajes del amor de Chapman?",
      options: [
        {
          optionKey: "pqp-c8-opcion-formas-de-dar-y-recibir",
          label:
            "Cinco formas principales en que las personas dan y reciben amor, para entender qué le llega a cada quien.",
        },
        {
          optionKey: "pqp-c8-opcion-tipos-de-persona",
          label:
            "Cinco tipos de persona, de modo que cada uno pertenece a uno y no cambia con el tiempo.",
        },
        {
          optionKey: "pqp-c8-opcion-test-de-compatibilidad",
          label:
            "Una prueba validada que permite medir cuánta compatibilidad hay entre dos personas.",
        },
      ],
    },
    summaryScene: {
      title: "Un vocabulario, no una casilla",
      body: [
        "Los cinco lenguajes sirven para poner nombre a lo que a cada quien le llega. Sirven menos como etiqueta, y nadie está obligado a caber en una.",
      ],
    },
  },
  {
    slug: "aprender-el-idioma-del-otro",
    practiceSlug: "el-mismo-gesto-en-dos-manos",
    title: "Aprender el idioma del otro",
    summary:
      "El capítulo dice algo incómodo y útil: no basta con decir «así soy yo» y esperar que el otro traduzca.",
    duration: "8–10 minutos",
    intro: {
      title: "Aprender el idioma del otro",
      body: [
        "El capítulo dice algo incómodo y útil: no basta con decir «así soy yo» y esperar que el otro traduzca.",
      ],
      note: "Trabajaremos con una escena inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Aprender el lenguaje del otro: un puente de ida y vuelta",
      body: "Lee esa sección y fíjate en la imagen que propone: ser bilingües emocionales.",
    },
    concept: {
      title: "Lo que sale fácil y lo que llega",
      body: [
        "El capítulo describe dos pasos: conocer qué necesita uno para sentirse querido, y aprender a expresarlo en la forma en que al otro le llega. Un gesto dado en el idioma propio puede ser sincero y aun así no aterrizar.",
        "Y aclara qué no es esto: no se trata de anular quién eres ni de renunciar a tu forma. La imagen que usa es la de dos personas que hablan su idioma, entienden el del otro y arman algo entre los dos.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa tu relación. Y esto describe a dos personas que quieren acercarse — no es una tarea que le corresponda a uno solo.",
    },
    practice: {
      title: "El mismo gesto en dos manos",
      body: [
        "El mismo gesto de una pareja inventada, recibido por dos personas distintas. Observa qué cambia.",
      ],
      note: "Es un caso editorial. Nada se marca como correcto: ningún gesto es mejor que otro, y el ejercicio solo pregunta qué haría falta saber.",
    },
    recall: {
      question:
        "Según el capítulo, ¿por qué no basta con expresar afecto a la manera de uno?",
      options: [
        {
          optionKey: "pqp-c8-opcion-puede-no-llegar",
          label:
            "Porque lo que a uno le sale naturalmente puede no ser lo que al otro le llega, y entonces el gesto se pierde por el camino.",
        },
        {
          optionKey: "pqp-c8-opcion-hay-que-renunciar",
          label:
            "Porque hay que renunciar a la forma propia de expresarse y adoptar por completo la del otro.",
        },
        {
          optionKey: "pqp-c8-opcion-esfuerzo-basta",
          label:
            "Porque lo que cuenta es el esfuerzo, y el otro debería reconocerlo sea cual sea la forma.",
        },
      ],
    },
    summaryScene: {
      title: "Ida y vuelta",
      body: [
        "Hablar el idioma del otro no es dejar de hablar el propio. Es que el gesto llegue a donde iba.",
      ],
    },
  },
  {
    slug: "aceptar-no-es-aguantar",
    practiceSlug: "lo-que-la-aceptacion-cubre",
    title: "Aceptar no es aguantar",
    summary:
      "«Aceptación incondicional» es de las frases que más fácil se malinterpretan. El capítulo se adelanta a eso.",
    duration: "8–10 minutos",
    intro: {
      title: "Aceptar no es aguantar",
      body: [
        "«Aceptación incondicional» es de las frases que más fácil se malinterpretan. El capítulo se adelanta a eso.",
      ],
      note: "Trabajaremos con escenas inventadas para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Otras formas esenciales de afecto",
      body: "Lee esa sección y en particular el párrafo sobre la aceptación incondicional.",
    },
    concept: {
      title: "Dos cosas que se parecen y no lo son",
      body: [
        "El capítulo describe la aceptación incondicional como amar al otro con sus luces y sombras: reconocer que nadie es perfecto y no pretender moldear a la otra persona a la propia medida.",
        "Y añade, con todas las letras, lo que no es: «No es resignarse ni tolerar todo». Aceptar quién es alguien no es lo mismo que aceptar lo que hace. Si algo te hace daño, seguir queriendo a esa persona no te obliga a soportarlo.",
      ],
      note: "Marcar esta escena registra que exploraste la idea. Si lo que hay que aguantar incluye miedo, desprecio o control, eso ya no es una cuestión de aceptación: el capítulo anterior habla de ello.",
    },
    practice: {
      title: "Lo que la aceptación cubre",
      body: [
        "Cuatro escenas inventadas. Distingue lo que describe una forma de ser de lo que describe un daño.",
      ],
      note: "Son casos editoriales, no tu vida. Nada se marca como correcto: el ejercicio solo separa dos cosas que la misma palabra suele juntar.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué NO significa la aceptación incondicional?",
      options: [
        {
          optionKey: "pqp-c8-opcion-no-es-resignarse",
          label:
            "No significa resignarse ni tolerarlo todo: es reconocer que nadie es perfecto, sin pretender moldear al otro a la propia medida.",
        },
        {
          optionKey: "pqp-c8-opcion-aceptar-todo",
          label:
            "Significa aceptar cualquier conducta, porque quien ama de verdad no pone condiciones.",
        },
        {
          optionKey: "pqp-c8-opcion-callar-molestias",
          label:
            "Significa guardarse las molestias para no desgastar la relación con reclamos.",
        },
      ],
    },
    summaryScene: {
      title: "Con luces y sombras",
      body: [
        "Aceptar es dejar de querer moldear a alguien. No es una obligación de soportar lo que duele.",
      ],
    },
  },
  {
    slug: "amar-tambien-es-actuar",
    practiceSlug: "del-sentir-al-gesto-que-llega",
    title: "No basta con estar",
    summary:
      "«Pero si ya sabe que la amo». El capítulo recoge esa frase de terapia y le responde.",
    duration: "8–10 minutos",
    intro: {
      title: "No basta con estar",
      body: [
        "«Pero si ya sabe que la amo». El capítulo recoge esa frase de terapia y le responde.",
      ],
      note: "Trabajaremos con un caso inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "¿Por qué es tan importante el afecto?",
      body: "Lee esa sección completa, incluidos los párrafos donde el autor responde a «yo sigo aquí, ¿acaso eso no basta?».",
    },
    concept: {
      title: "Sentirlo y que se note",
      body: [
        "El capítulo sostiene que amar no es solo sentir, sino también actuar: se puede querer mucho a alguien y, si no se le demuestra, esa persona puede sentirse sola o poco valorada aunque el afecto siga intacto.",
        "De ahí su respuesta a «yo sigo aquí»: no basta solo con estar. La permanencia física y la presencia son cosas distintas, y lo que sostiene el vínculo día a día es la segunda.",
      ],
      note: "Marcar esta escena registra que exploraste la idea. Y esto no significa que quien no lo expresa quiera menos: el capítulo distingue lo que se siente de lo que llega.",
    },
    practice: {
      title: "Del sentir al gesto que llega",
      body: [
        "Ordena los pasos de un caso inventado, desde lo que alguien siente hasta que la otra persona lo nota.",
      ],
      note: "Es un caso editorial, no tu relación. Ordenarlo no es una receta: no existe una secuencia obligatoria para querer a alguien.",
    },
    recall: {
      question:
        "Según el capítulo, ¿por qué no basta con sentir el amor sin demostrarlo?",
      options: [
        {
          optionKey: "pqp-c8-opcion-puede-sentirse-sola",
          label:
            "Porque se puede querer profundamente a alguien y, si no se le demuestra, esa persona puede sentirse sola o poco valorada.",
        },
        {
          optionKey: "pqp-c8-opcion-el-sentimiento-desaparece",
          label:
            "Porque el sentimiento se va apagando hasta desaparecer si no se expresa.",
        },
        {
          optionKey: "pqp-c8-opcion-permanecer-basta",
          label:
            "Porque permanecer y cumplir con lo práctico ya es, en sí mismo, la mejor demostración.",
        },
      ],
    },
    summaryScene: {
      title: "Que se note",
      body: [
        "Sentirlo y demostrarlo no son lo mismo. El capítulo insiste en lo segundo porque es lo único que la otra persona puede ver.",
      ],
    },
  },
  {
    slug: "triangulo-de-sternberg",
    practiceSlug: "que-vertice-sostiene-la-escena",
    title: "Tres vértices para describir el amor",
    summary:
      "El capítulo cierra con un modelo clásico. Vale la pena saber qué es un modelo antes de usarlo.",
    duration: "8–10 minutos",
    intro: {
      title: "Tres vértices para describir el amor",
      body: [
        "El capítulo cierra con un modelo clásico. Vale la pena saber qué es un modelo antes de usarlo.",
      ],
      note: "Trabajaremos con descripciones inventadas para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "El triángulo del amor de Sternberg",
      body: "Lee la sección final del capítulo, donde describe los tres vértices y qué ocurre cuando uno solo sostiene la relación.",
    },
    concept: {
      title: "Un modelo, no una medida",
      body: [
        "El capítulo recoge el modelo que Robert Sternberg propuso en 1986: describir el amor como un triángulo de tres componentes —pasión, intimidad y compromiso— y observar que una relación sostenida por uno solo tiende a quedarse corta.",
        "Es un modelo teórico: una manera de describir y conversar sobre el amor, no un instrumento que mida el de nadie. No hay una combinación correcta de los tres, ni un reparto que prediga cómo terminará una relación.",
      ],
      note: "Marcar esta escena registra que exploraste la idea. El modelo describe; no puntúa relaciones ni anticipa lo que va a pasar con la tuya.",
    },
    practice: {
      title: "¿Qué vértice sostiene la escena?",
      body: [
        "Tres descripciones inventadas de tres parejas. Reconoce qué vértice describe cada una.",
      ],
      note: "Se clasifican descripciones, no relaciones. No hay respuesta correcta ni puntaje, y ninguna combinación es mejor ni predice nada.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué tres elementos componen el triángulo del amor propuesto por Sternberg?",
      options: [
        {
          optionKey: "pqp-c8-opcion-pasion-intimidad-compromiso",
          label: "Pasión, intimidad y compromiso.",
        },
        {
          optionKey: "pqp-c8-opcion-confianza-respeto-comunicacion",
          label: "Confianza, respeto y comunicación.",
        },
        {
          optionKey: "pqp-c8-opcion-atraccion-costumbre-proyecto",
          label: "Atracción, costumbre y proyecto compartido.",
        },
      ],
    },
    summaryScene: {
      title: "Para describir, no para calificar",
      body: [
        "Los tres vértices son un vocabulario para hablar del amor. Sirven para nombrar lo que hay, no para calificar lo que falta.",
      ],
    },
  },
];

export const PQP_C08_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C08_MICROGUIDES.map((m) => microguidePresentation(PQP_C08, m));

export const PQP_C08_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C08_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C08, m));
