/**
 * PQP-C03's 4 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C03` from
 * `scripts/pqp/chapters/c03.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C03: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 4 — unit 1 is the front matter.
  keyPrefix: "pqp-c3",
  chapterLabel: "capítulo 3",
};

export const PQP_C03_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "elegir-cada-dia",
    practiceSlug: "eleccion-o-inercia",
    title: "Elegir, no solo permanecer",
    summary:
      "«Seguimos juntos» y «nos elegimos» pueden describir la misma situación y significar cosas distintas. El capítulo empieza por separarlas.",
    duration: "8–10 minutos",
    intro: {
      title: "Elegir, no solo permanecer",
      body: [
        "«Seguimos juntos» y «nos elegimos» pueden describir la misma situación y significar cosas distintas. El capítulo empieza por separarlas.",
      ],
      note: "Trabajaremos con casos inventados para el ejercicio, no con tu historia. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "El verdadero significado del compromiso",
      body: "Lee la sección donde el capítulo define el compromiso, y fíjate en qué lo distingue de un sentimiento intenso.",
    },
    concept: {
      title: "Una elección que se renueva",
      body: [
        "El capítulo describe el compromiso como algo que se sostiene con conductas: cuidar el vínculo, atravesar dificultades juntos, mantener la confianza. No como un estado que, una vez alcanzado, se conserva solo.",
        "De ahí la distinción que da nombre al capítulo: permanecer es una situación; elegirse es algo que se hace, y se puede volver a hacer.",
      ],
      note: "Una precisión de FeelVerse, no del capítulo: elegir no significa quedarse pase lo que pase. Nada de esta guía sostiene permanecer donde hay violencia, coerción, control o miedo, y ahí la pregunta no es cuánto compromiso hay sino qué protección hace falta. Marcar la escena registra que exploraste la idea; no evalúa tu relación.",
    },
    practice: {
      title: "¿Elección o inercia?",
      body: [
        "Cuatro situaciones inventadas. Distingue en cuáles se describe una elección sostenida y en cuáles simplemente una continuidad.",
      ],
      note: "Son casos editoriales. La clasificación no juzga a las parejas descritas: nombra qué se ve en cada escena.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué describe mejor el compromiso en una relación?",
      options: [
        {
          optionKey: "pqp-c3-opcion-eleccion-renovada",
          label:
            "Una elección que se sostiene y se renueva con conductas concretas a lo largo del tiempo.",
        },
        {
          optionKey: "pqp-c3-opcion-permanecer-pase-lo-que-pase",
          label:
            "Permanecer en la relación pase lo que pase, como prueba de que el compromiso es real.",
        },
        {
          optionKey: "pqp-c3-opcion-sentimiento-intenso",
          label:
            "Un sentimiento lo bastante intenso como para que las dificultades no lo afecten.",
        },
      ],
    },
    summaryScene: {
      title: "Elegirse es un verbo",
      body: [
        "El compromiso, tal como lo describe el capítulo, se parece más a algo que se hace que a algo que se tiene.",
        "Y no equivale a permanecer a cualquier precio: eso es otra cosa, y no es lo que esta guía propone.",
      ],
    },
  },
  {
    slug: "priorizar-es-agenda",
    practiceSlug: "lo-que-se-mueve-y-lo-que-no",
    title: "Priorizar se ve en la agenda",
    summary:
      "Casi nadie diría que su relación no es una prioridad. El capítulo propone mirar dónde se nota eso, y no es en la intención.",
    duration: "8–10 minutos",
    intro: {
      title: "Priorizar se ve en la agenda",
      body: [
        "Casi nadie diría que su relación no es una prioridad. El capítulo propone mirar dónde se nota eso, y no es en la intención.",
      ],
      note: "Trabajaremos con una agenda inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "2. Priorizar la relación",
      body: "Lee la sección sobre reservar tiempo, y fíjate en qué hace que ese tiempo sea distinto del que queda libre.",
    },
    concept: {
      title: "Lo que no se mueve",
      body: [
        "El capítulo describe la prioridad como algo que se reserva antes, no como lo que queda después. Un tiempo que no se negocia frente a lo urgente es lo que distingue una prioridad de una intención.",
        "No dice cuánto tiene que ser ni con qué frecuencia. Dice que exista y que se sostenga.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa cómo repartes tu tiempo ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "Lo que se mueve y lo que no",
      body: [
        "Una misma semana inventada, en dos versiones. Observa qué cambia según qué se considera movible.",
      ],
      note: "Es una agenda editorial, no la tuya. Nada se marca como correcto o incorrecto.",
    },
    recall: {
      question:
        "Según el capítulo, ¿en qué se nota que una pareja prioriza su relación?",
      options: [
        {
          optionKey: "pqp-c3-opcion-tiempo-reservado",
          label:
            "En que reservan tiempo y atención de forma deliberada, incluso cuando la agenda está llena.",
        },
        {
          optionKey: "pqp-c3-opcion-cuando-sobra-tiempo",
          label:
            "En que aprovechan bien los ratos que sobran cuando el resto de obligaciones lo permite.",
        },
        {
          optionKey: "pqp-c3-opcion-intensidad",
          label:
            "En que sus momentos juntos son especialmente intensos, aunque sean poco frecuentes.",
        },
      ],
    },
    summaryScene: {
      title: "Antes, no después",
      body: [
        "Una prioridad se reconoce en lo que se reserva de antemano y en lo que no se mueve cuando aparece lo urgente.",
      ],
    },
  },
  {
    slug: "aceptar-sin-coincidir",
    practiceSlug: "diferencia-o-desacuerdo",
    title: "Aceptar no es coincidir",
    summary:
      "Aceptar a alguien suele confundirse con darle la razón. El capítulo separa las dos cosas.",
    duration: "8–10 minutos",
    intro: {
      title: "Aceptar no es coincidir",
      body: [
        "Aceptar a alguien suele confundirse con darle la razón. El capítulo separa las dos cosas.",
      ],
      note: "Trabajaremos con ejemplos inventados para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "2. Practiquen la aceptación y el respeto mutuo",
      body: "Lee la sección sobre aceptar las diferencias, y fíjate en qué NO exige.",
    },
    concept: {
      title: "Diferencia no es desacuerdo",
      body: [
        "Aceptar, tal como lo plantea el capítulo, es respetar que la otra persona sea distinta: en gustos, en ritmo, en forma de ver las cosas. No pide coincidir, y no pide dejar de tener criterio.",
        "Conviene separarlo también de otra cosa: aceptar una diferencia de carácter no es lo mismo que aceptar cualquier conducta. Se puede respetar a alguien y a la vez objetar lo que hace.",
      ],
      note: "Esa segunda distinción es de FeelVerse, no del capítulo, y está aquí a propósito: «aceptación» no significa renunciar a poner límites. Marcar la escena registra que exploraste la idea.",
    },
    practice: {
      title: "¿Diferencia o desacuerdo?",
      body: [
        "Varias situaciones inventadas. Distingue lo que es una diferencia entre dos personas de lo que es un desacuerdo sobre algo concreto.",
      ],
      note: "Son casos editoriales. Distinguirlos no dice cuál importa más: dice qué tipo de conversación pide cada uno.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué significa aceptar a la otra persona tal como es?",
      options: [
        {
          optionKey: "pqp-c3-opcion-respetar-diferencia",
          label:
            "Respetar su individualidad aunque no se coincida con ella en todo.",
        },
        {
          optionKey: "pqp-c3-opcion-estar-de-acuerdo",
          label:
            "Llegar a estar de acuerdo en lo esencial, para que las diferencias dejen de pesar.",
        },
        {
          optionKey: "pqp-c3-opcion-tolerar-todo",
          label:
            "Tolerar cualquier conducta suya sin plantear objeciones, porque objetar sería no aceptarla.",
        },
      ],
    },
    summaryScene: {
      title: "Respetar sin coincidir",
      body: [
        "Aceptar es respetar que alguien sea distinto, no llegar a pensar igual.",
        "Y respetar a una persona sigue siendo compatible con objetar algo que hace.",
      ],
    },
  },
  {
    slug: "apoyar-el-crecimiento",
    practiceSlug: "acompanar-un-proyecto",
    title: "Apoyar lo que le hace crecer",
    summary:
      "Que a alguien le vaya bien por su cuenta puede vivirse como una amenaza o como algo compartido. El capítulo propone lo segundo, y explica en qué se nota.",
    duration: "8–10 minutos",
    intro: {
      title: "Apoyar lo que le hace crecer",
      body: [
        "Que a alguien le vaya bien por su cuenta puede vivirse como una amenaza o como algo compartido. El capítulo propone lo segundo, y explica en qué se nota.",
      ],
      note: "Trabajaremos con un proyecto inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "6. Sean apoyo para el crecimiento personal del otro",
      body: "Lee la sección sobre acompañar los proyectos del otro, y fíjate en la frase con la que cierra.",
    },
    concept: {
      title: "Un vínculo que no encierra",
      body: [
        "El capítulo describe una relación comprometida como una que acompaña lo que cada uno quiere para su vida, en vez de vivirlo como una pérdida o una competencia.",
        "Apoyar así es concreto: implica tiempo, esfuerzo y a veces incomodidad. No es solo no oponerse.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa cuánto se apoyan ustedes ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "Acompañar un proyecto",
      body: [
        "Ordena los pasos de un caso inventado, desde que aparece el proyecto de una persona hasta que el apoyo se vuelve algo concreto.",
      ],
      note: "Es un caso editorial, no tu historia.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué papel tiene el crecimiento personal de cada uno dentro de la relación?",
      options: [
        {
          optionKey: "pqp-c3-opcion-impulsa",
          label:
            "Una relación comprometida acompaña e impulsa los proyectos propios de cada persona.",
        },
        {
          optionKey: "pqp-c3-opcion-postergar",
          label:
            "Los proyectos individuales conviene postergarlos mientras la relación se consolida.",
        },
        {
          optionKey: "pqp-c3-opcion-independiente",
          label:
            "El crecimiento de cada uno es asunto individual y es mejor mantenerlo al margen del vínculo.",
        },
      ],
    },
    summaryScene: {
      title: "Acompañar cuesta algo",
      body: [
        "Apoyar el crecimiento del otro se nota en lo concreto: tiempo, esfuerzo, a veces incomodidad. No basta con no oponerse.",
      ],
    },
  },
];

export const PQP_C03_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C03_MICROGUIDES.map((m) => microguidePresentation(PQP_C03, m));

export const PQP_C03_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C03_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C03, m));
