/**
 * PQP-C07's 4 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C07` from
 * `scripts/pqp/chapters/c07.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C07: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 8 — unit 1 is the front matter.
  keyPrefix: "pqp-c7",
  chapterLabel: "capítulo 7",
};

export const PQP_C07_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "limite-no-es-rechazo",
    practiceSlug: "un-limite-o-un-reproche",
    title: "Un límite no es un rechazo",
    summary:
      "El capítulo empieza por aquí: lo que un límite protege, y por qué ponerlo no es alejarse.",
    duration: "8–10 minutos",
    intro: {
      title: "Un límite no es un rechazo",
      body: [
        "El capítulo empieza por aquí: lo que un límite protege, y por qué ponerlo no es alejarse.",
      ],
      note: "Trabajaremos con frases inventadas para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "El respeto empieza con los límites",
      body: "Lee la sección sobre los límites y fíjate en la imagen que usa el capítulo: cercas, no muros.",
    },
    concept: {
      title: "Lo que la cerca guarda dentro",
      body: [
        "El capítulo describe los límites como cercas invisibles que resguardan la integridad emocional: dentro viven los valores, las memorias y las necesidades de cada uno. No están puestas contra el otro.",
        "También nombra lo que ocurre cuando esa frontera se invade una y otra vez: la persona empieza a apagarse, deja de hablar, deja de pedir. Por eso ponerlo en palabras protege algo propio, y no es un rechazo.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa tu relación. Y si nombrar un límite te trajera consecuencias, eso no es un problema de cómo lo dijiste: la última guía de este capítulo habla de eso.",
    },
    practice: {
      title: "¿Un límite o un reproche?",
      body: [
        "Cuatro frases inventadas. Fíjate en cuáles nombran algo propio y cuáles califican al otro.",
      ],
      note: "Frases editoriales, no tuyas. Nada se marca como correcto: ninguna frase está prohibida y ordenarlas solo sirve para notar la diferencia.",
    },
    recall: {
      question: "Según el capítulo, ¿qué son los límites emocionales?",
      options: [
        {
          optionKey: "pqp-c7-opcion-cercas-que-resguardan",
          label:
            "Cercas invisibles que resguardan la integridad emocional de cada uno, no muros que separan.",
        },
        {
          optionKey: "pqp-c7-opcion-reglas-al-otro",
          label:
            "Reglas que se le ponen al otro para que corrija lo que hace mal.",
        },
        {
          optionKey: "pqp-c7-opcion-senal-de-desconfianza",
          label:
            "Una señal de que todavía falta confianza, y que se van necesitando menos con los años.",
        },
      ],
    },
    summaryScene: {
      title: "Cercas, no muros",
      body: [
        "Un límite dice qué necesitas para seguir siendo tú. Eso protege el vínculo en lugar de amenazarlo.",
      ],
    },
  },
  {
    slug: "hablar-del-otro-sin-testigos",
    practiceSlug: "la-misma-broma-en-dos-mesas",
    title: "Cómo hablas de tu pareja cuando no está",
    summary:
      "El respeto no se mide solo en la intimidad. El capítulo se detiene en lo que pasa delante de otros.",
    duration: "8–10 minutos",
    intro: {
      title: "Cómo hablas de tu pareja cuando no está",
      body: [
        "El respeto no se mide solo en la intimidad. El capítulo se detiene en lo que pasa delante de otros.",
      ],
      note: "Trabajaremos con una escena inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Comunicación y cuidado como expresión de respeto",
      body: "Lee esa sección, y en particular la parte sobre cómo hablas del otro cuando no te escucha.",
    },
    concept: {
      title: "El chiste que no era solo un chiste",
      body: [
        "El capítulo señala que el sarcasmo puede ser una forma encubierta de desprecio, y que ridiculizar al otro —aunque sea en broma y aunque todos se rían— puede dañar la autoestima y romper la complicidad.",
        "Y añade una pregunta que no depende de estar delante: cómo hablas de tu pareja cuando no está. Hablar bien del otro sin testigos es cuidar el vínculo cuando nadie lo está mirando.",
      ],
      note: "No todo el humor compartido es desprecio, y el capítulo no propone dejar de bromear. Marcar esta escena registra que exploraste la idea; no evalúa tu relación ni la de nadie.",
    },
    practice: {
      title: "La misma broma en dos mesas",
      body: [
        "La misma broma de una pareja inventada, en dos situaciones. Observa qué podría cambiar.",
      ],
      note: "Es un caso editorial. Nada se marca como correcto: el ejercicio solo pregunta qué haría falta saber.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué pueden ser las bromas a costa de la pareja delante de otros?",
      options: [
        {
          optionKey: "pqp-c7-opcion-desprecio-encubierto",
          label:
            "Una forma encubierta de desprecio, capaz de dañar la autoestima y romper la complicidad.",
        },
        {
          optionKey: "pqp-c7-opcion-muestra-de-confianza",
          label:
            "Una muestra de confianza y complicidad que en general fortalece el vínculo.",
        },
        {
          optionKey: "pqp-c7-opcion-susceptibilidad",
          label:
            "Un asunto de susceptibilidad de quien se molesta, más que del contenido de la broma.",
        },
      ],
    },
    summaryScene: {
      title: "También cuando nadie mira",
      body: [
        "Lo que se dice del otro en su ausencia forma parte del vínculo, aunque el otro no llegue a enterarse.",
      ],
    },
  },
  {
    slug: "quien-decide-en-casa",
    practiceSlug: "de-quien-decide-a-como-decidimos",
    title: "Quién decide, y sobre qué",
    summary:
      "El dinero, la casa, los hijos, las vacaciones. El capítulo mira quién decide y qué deja eso.",
    duration: "8–10 minutos",
    intro: {
      title: "Quién decide, y sobre qué",
      body: [
        "El dinero, la casa, los hijos, las vacaciones. El capítulo mira quién decide y qué deja eso.",
      ],
      note: "Trabajaremos con un caso inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Dinámicas de poder: machismo, dinero y decisiones",
      body: "Lee esa sección y fíjate en cómo describe el capítulo lo que parece práctico y no lo es.",
    },
    concept: {
      title: "Lo que parece práctico",
      body: [
        "El capítulo describe cómo, en muchas parejas y sin que nadie lo note, uno de los dos empieza a decidir casi todo. Puede parecer eficiencia, y aun sin mala intención los efectos son reales: uno se siente solo o infantilizado, el otro carga un peso excesivo.",
        "Nombra también el machismo operando en silencio —«eso es cosa de mujeres», el cuidado como responsabilidad de una sola parte— y dice que cuestionar esos patrones no es un ataque.",
      ],
      note: "Esto describe arreglos que dos personas pueden mirar juntas. Si plantearlo trajera castigo, silencio prolongado o miedo, ya no es un problema de reparto: la última guía de este capítulo habla de eso.",
    },
    practice: {
      title: "De «quién decide» a «cómo decidimos»",
      body: [
        "Ordena los pasos de un caso inventado, desde que nadie lo ha nombrado hasta que hay algo concreto.",
      ],
      note: "Es un caso editorial, no tu casa. Y describe un arreglo entre dos personas que pueden hablar con libertad — no toda situación lo es.",
    },
    recall: {
      question:
        "Según el capítulo, ¿por qué importa una distribución desigual de las decisiones aunque no haya mala intención?",
      options: [
        {
          optionKey: "pqp-c7-opcion-efectos-reales",
          label:
            "Porque los efectos son reales igualmente: uno se siente solo o invisible, el otro carga un peso excesivo, y aparecen resentimiento o distancia.",
        },
        {
          optionKey: "pqp-c7-opcion-si-funciona-da-igual",
          label:
            "No importa mientras la casa funcione y ninguno de los dos se queje.",
        },
        {
          optionKey: "pqp-c7-opcion-solo-dinero",
          label:
            "Importa solo cuando se trata de dinero; en el resto de los temas es cuestión de eficiencia.",
        },
      ],
    },
    summaryScene: {
      title: "El reparto se nota tarde",
      body: [
        "Un reparto desigual rara vez se ve a simple vista. Sus efectos aparecen después, y son reales aunque nadie lo haya querido así.",
      ],
    },
  },
  {
    slug: "reconocer-la-violencia",
    practiceSlug: "las-formas-que-nombra-el-capitulo",
    title: "La línea que no se cruza",
    summary:
      "El capítulo dedica una sección entera a esto y no la suaviza. Esta guía tampoco.",
    duration: "8–10 minutos",
    intro: {
      title: "La línea que no se cruza",
      body: [
        "El capítulo dedica una sección entera a esto y no la suaviza. Esta guía tampoco.",
      ],
      note: "Puede ser difícil de leer. No se te pedirá contar nada tuyo en ningún momento, y puedes salir y volver cuando quieras.",
    },
    passage: {
      title: "Violencia: la línea que nunca debe cruzarse",
      body: "Lee la sección completa, incluidas las cinco formas que enumera y los dos párrafos que la cierran.",
    },
    concept: {
      title: "No empieza con un golpe",
      body: [
        "El capítulo es explícito: la violencia no es «una pérdida momentánea de control» ni «una forma intensa de discutir». Y no siempre empieza con un golpe — puede instalarse en el desprecio, la manipulación, el control del dinero, el aislamiento o las amenazas disfrazadas de preocupación.",
        "Nombra cinco formas: física, verbal, emocional, sexual y económica. Y cierra con dos frases que conviene leer despacio: si esa línea se ha cruzado, la prioridad es buscar ayuda profesional y garantizar la seguridad, no salvar la relación. Nadie merece quedarse donde es maltratado.",
      ],
      note: "Esta guía no evalúa tu situación ni la clasifica. Si algo de esto describe tu vida, tienes derecho a pedir ayuda ahora: alguien de confianza, un profesional o un servicio de atención de tu país.",
    },
    practice: {
      title: "Las formas que nombra el capítulo",
      body: [
        "Cuatro escenas inventadas, ninguna con un golpe. Reconoce cuál de las formas del capítulo nombra cada una.",
      ],
      note: "No hay respuesta correcta ni puntaje: es un ejercicio de reconocimiento. Ninguna de estas formas es más leve que otra, y no se te pide contar nada tuyo.",
    },
    recall: {
      question:
        "Según el capítulo, cuando ha aparecido la violencia, ¿cuál es la prioridad?",
      options: [
        {
          optionKey: "pqp-c7-opcion-seguridad-y-ayuda",
          label:
            "Buscar ayuda profesional y garantizar la seguridad, no salvar la relación.",
        },
        {
          optionKey: "pqp-c7-opcion-mejorar-comunicacion",
          label:
            "Trabajar la comunicación de la pareja para que no vuelva a repetirse.",
        },
        {
          optionKey: "pqp-c7-opcion-parte-de-cada-uno",
          label: "Que cada uno reconozca la parte que le toca en lo que pasó.",
        },
      ],
    },
    summaryScene: {
      title: "Primero la seguridad",
      body: [
        "El capítulo lo deja dicho sin condiciones: por mucha historia compartida que haya, nadie merece quedarse en una relación donde es maltratado o maltratada.",
        "Si necesitas hablarlo, pedir ayuda es una opción disponible ahora — alguien de confianza, un profesional o un servicio de atención de tu país. No hace falta tener pruebas ni estar seguro para preguntar.",
      ],
    },
  },
];

export const PQP_C07_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C07_MICROGUIDES.map((m) => microguidePresentation(PQP_C07, m));

export const PQP_C07_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C07_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C07, m));
