/**
 * PQP-C04's 4 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C04` from
 * `scripts/pqp/chapters/c04.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C04: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 5 — unit 1 is the front matter.
  keyPrefix: "pqp-c4",
  chapterLabel: "capítulo 4",
};

export const PQP_C04_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "hablar-no-es-comunicarse",
    practiceSlug: "en-que-nivel-ocurre",
    title: "Hablar no es comunicarse",
    summary:
      "Dos personas pueden hablarse todos los días y llevar años sin contarse nada. El capítulo empieza por ahí.",
    duration: "8–10 minutos",
    intro: {
      title: "Hablar no es comunicarse",
      body: [
        "Dos personas pueden hablarse todos los días y llevar años sin contarse nada. El capítulo empieza por ahí.",
      ],
      note: "Trabajaremos con intercambios inventados para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Los niveles de la comunicación",
      body: "Lee la sección donde el capítulo distingue distintos niveles de conversación, del más rutinario al más personal.",
    },
    concept: {
      title: "No todo lo que se dice llega al mismo sitio",
      body: [
        "El capítulo describe la conversación por capas: lo rutinario, lo informativo, lo que se piensa, lo que se siente. Ninguna sobra —la logística también hace falta—, pero quedarse solo en las primeras puede convivir con años de distancia.",
        "Por eso la cantidad de palabras no dice mucho por sí sola. Lo que cambia es a qué nivel llega la conversación.",
      ],
      note: "Un límite importante: hablar mejor ayuda con los malentendidos, no con el daño. Si alguien intimida, amenaza, controla o agrede, eso no es un problema de comunicación y no se resuelve eligiendo mejor las palabras — ahí lo que hace falta es protección y apoyo, no una técnica.",
    },
    practice: {
      title: "¿En qué nivel ocurre?",
      body: [
        "Varios intercambios inventados. Distingue los que se quedan en lo práctico de los que abren algo personal.",
      ],
      note: "Son intercambios editoriales, no los tuyos. Ningún nivel es mejor que otro: el ejercicio es notar dónde ocurre cada uno.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué distingue hablar de comunicarse en una pareja?",
      options: [
        {
          optionKey: "pqp-c4-opcion-niveles",
          label:
            "Que se puede hablar mucho quedándose en niveles superficiales y no llegar nunca a lo que a cada uno le importa.",
        },
        {
          optionKey: "pqp-c4-opcion-cantidad",
          label:
            "Que comunicarse exige dedicar más tiempo del que la mayoría de las parejas dedica a hablar.",
        },
        {
          optionKey: "pqp-c4-opcion-tecnica",
          label:
            "Que comunicarse requiere una técnica concreta y hablar es lo que se hace sin ella.",
        },
      ],
    },
    summaryScene: {
      title: "La capa, no la cantidad",
      body: [
        "Lo que distingue hablar de comunicarse no es cuánto se habla, sino a qué capa llega la conversación.",
        "Y conviene recordar el límite: esto sirve para entenderse mejor, no para reparar un daño.",
      ],
    },
  },
  {
    slug: "armonia-no-es-salud",
    practiceSlug: "armonia-o-distancia",
    title: "No pelear no es lo mismo que estar conectados",
    summary:
      "«Nosotros nunca discutimos» suele decirse con orgullo. El capítulo propone mirarlo dos veces.",
    duration: "8–10 minutos",
    intro: {
      title: "No pelear no es lo mismo que estar conectados",
      body: [
        "«Nosotros nunca discutimos» suele decirse con orgullo. El capítulo propone mirarlo dos veces.",
      ],
      note: "Trabajaremos con una escena inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "2. Comunicación de hechos: la crónica del día",
      body: "Lee la sección sobre las parejas que organizan bien la vida práctica, y fíjate en qué llama el capítulo «la trampa».",
    },
    concept: {
      title: "Ausencia de conflicto no es presencia de vínculo",
      body: [
        "Una pareja puede coordinarse perfectamente y no hablar de nada que le importe a ninguno de los dos. No discuten porque no se exponen.",
        "El capítulo no dice que discutir sea bueno ni que la calma sea sospechosa. Dice que la ausencia de conflicto, por sí sola, no informa de si hay conexión.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa cuánto discuten ustedes ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "¿Armonía o distancia?",
      body: [
        "Las mismas señales de una semana tranquila, en dos situaciones distintas. Observa qué podría cambiar lo que significan.",
      ],
      note: "Es un caso editorial. Nada se marca como correcto o incorrecto.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué riesgo tiene una pareja que casi nunca discute?",
      options: [
        {
          optionKey: "pqp-c4-opcion-ausencia-no-es-conexion",
          label:
            "Que la ausencia de discusiones se confunda con conexión, cuando puede convivir con no hablar de nada personal.",
        },
        {
          optionKey: "pqp-c4-opcion-explotara",
          label:
            "Que lo no hablado se acumule hasta estallar en una discusión mucho mayor.",
        },
        {
          optionKey: "pqp-c4-opcion-ninguno",
          label:
            "Ninguno: no discutir es el mejor indicador de que una relación funciona.",
        },
      ],
    },
    summaryScene: {
      title: "La calma no es un diagnóstico",
      body: [
        "No discutir no dice, por sí solo, si una pareja está conectada o distante. Es una señal que necesita contexto.",
      ],
    },
  },
  {
    slug: "pensar-distinto-sin-dividirse",
    practiceSlug: "el-miedo-debajo-de-la-opinion",
    title: "Pensar distinto no divide",
    summary:
      "Hay opiniones que no se dicen por miedo a lo que revelarían. El capítulo cuenta qué pasó cuando se dijeron.",
    duration: "8–10 minutos",
    intro: {
      title: "Pensar distinto no divide",
      body: [
        "Hay opiniones que no se dicen por miedo a lo que revelarían. El capítulo cuenta qué pasó cuando se dijeron.",
      ],
      note: "Trabajaremos con un caso inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "3. Comunicación de ideas: pensar distinto sin dividirse",
      body: "Lee la sección sobre mostrar las propias ideas, y fíjate en qué temía cada uno antes de hacerlo.",
    },
    concept: {
      title: "El miedo suele estar debajo",
      body: [
        "Cuando dos personas evitan un tema de fondo, muchas veces no es el tema lo que evitan: es lo que temen que su postura diga de ellas.",
        "El capítulo describe que nombrar ese temor cambió la conversación, y que mostrar la diferencia no separó a la pareja sino que les permitió conocerse mejor.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no interpreta tus silencios ni te atribuye ningún miedo.",
    },
    practice: {
      title: "El miedo debajo de la opinión",
      body: [
        "Ordena los pasos de un caso inventado, desde el tema que no se saca hasta lo que aparece cuando sí se saca.",
      ],
      note: "Es un caso editorial, no tu historia.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué suele ocurrir cuando una pareja se muestra sus opiniones distintas sobre algo importante?",
      options: [
        {
          optionKey: "pqp-c4-opcion-se-conocen-mas",
          label:
            "Que llegan a conocerse mejor, en lugar de dividirse como a veces temen.",
        },
        {
          optionKey: "pqp-c4-opcion-mejor-evitar",
          label:
            "Que conviene evitarlo en los temas de fondo, para no abrir distancias innecesarias.",
        },
        {
          optionKey: "pqp-c4-opcion-hay-que-convencer",
          label:
            "Que uno de los dos acabará convenciendo al otro si expone bien sus razones.",
        },
      ],
    },
    summaryScene: {
      title: "Mostrar la diferencia",
      body: [
        "Mostrar una opinión distinta no separó a la pareja del capítulo: les permitió conocerse mejor.",
        "El objetivo no era convencer a nadie.",
      ],
    },
  },
  {
    slug: "validar-no-es-dar-la-razon",
    practiceSlug: "validar-o-ceder",
    title: "Validar no es dar la razón",
    summary:
      "Reconocer lo que alguien siente suele confundirse con aceptar que tiene razón. Son cosas distintas, y el capítulo las separa.",
    duration: "8–10 minutos",
    intro: {
      title: "Validar no es dar la razón",
      body: [
        "Reconocer lo que alguien siente suele confundirse con aceptar que tiene razón. Son cosas distintas, y el capítulo las separa.",
      ],
      note: "Trabajaremos con respuestas inventadas para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "7. Valida al otro",
      body: "Lee la sección sobre validar, y fíjate en la primera frase: dice explícitamente qué NO es.",
    },
    concept: {
      title: "Reconocer sin renunciar",
      body: [
        "Validar es decirle a alguien que lo que siente tiene sentido desde donde está. No exige compartir su interpretación, ni retirar la propia, ni aceptar lo que pide.",
        "Es una distinción útil porque hace posible acercarse sin ceder: se puede reconocer lo que el otro siente y seguir sosteniendo una postura distinta.",
      ],
      note: "Un límite importante: hablar mejor ayuda con los malentendidos, no con el daño. Si alguien intimida, amenaza, controla o agrede, eso no es un problema de comunicación y no se resuelve eligiendo mejor las palabras — ahí lo que hace falta es protección y apoyo, no una técnica. Validar no es una forma de acomodarse a quien hace daño, y esta guía no lo propone para eso.",
    },
    practice: {
      title: "¿Validar o ceder?",
      body: [
        "Varias respuestas inventadas a una misma escena. Distingue las que reconocen lo que el otro siente de las que renuncian a la propia postura.",
      ],
      note: "Son respuestas editoriales, no las tuyas. Ninguna está prohibida: el ejercicio es notar qué hace cada una.",
    },
    recall: {
      question: "Según el capítulo, ¿qué significa validar a la otra persona?",
      options: [
        {
          optionKey: "pqp-c4-opcion-reconocer-sentir",
          label:
            "Reconocer que lo que siente tiene sentido para ella, aunque no se comparta su punto de vista.",
        },
        {
          optionKey: "pqp-c4-opcion-darle-razon",
          label: "Aceptar que tiene razón para que la conversación no escale.",
        },
        {
          optionKey: "pqp-c4-opcion-callar",
          label:
            "Guardarse la propia opinión mientras la otra persona está alterada.",
        },
      ],
    },
    summaryScene: {
      title: "Acercarse sin ceder",
      body: [
        "Validar reconoce lo que el otro siente y deja intacta la propia postura. No es dar la razón ni callarse.",
        "Y no es una herramienta para sostener una situación que hace daño.",
      ],
    },
  },
];

export const PQP_C04_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C04_MICROGUIDES.map((m) => microguidePresentation(PQP_C04, m));

export const PQP_C04_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C04_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C04, m));
