/**
 * PQP-C02's 5 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C02` from
 * `scripts/pqp/chapters/c02.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C02: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 3 — unit 1 is the front matter.
  keyPrefix: "pqp-c2",
  chapterLabel: "capítulo 2",
};

export const PQP_C02_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "queja-no-es-critica",
    practiceSlug: "sobre-el-hecho-o-sobre-la-persona",
    title: "Una queja no es una crítica",
    summary:
      "Dos frases pueden decir lo mismo y hacer cosas muy distintas. El capítulo empieza por ahí: hay una diferencia entre nombrar algo que pasó y decirle a alguien cómo es.",
    duration: "8–10 minutos",
    intro: {
      title: "Una queja no es una crítica",
      body: [
        "Dos frases pueden decir lo mismo y hacer cosas muy distintas. El capítulo empieza por ahí: hay una diferencia entre nombrar algo que pasó y decirle a alguien cómo es.",
      ],
      note: "Trabajaremos con frases inventadas para el ejercicio, no con las tuyas. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Primer Jinete: La Crítica",
      body: "Lee la sección donde el capítulo distingue la crítica de una molestia expresada, y fíjate en qué propone en su lugar.",
    },
    concept: {
      title: "Sobre el hecho, o sobre la persona",
      body: [
        "Una queja habla de algo concreto que ocurrió y de lo que uno necesita. Una crítica generaliza eso hasta convertirlo en un rasgo del otro: de «esto pasó» a «tú eres así».",
        "La diferencia importa porque cambian las respuestas posibles. Frente a un hecho concreto se puede hacer algo; frente a una definición de quién eres, casi solo queda defenderse.",
      ],
      note: "Es lenguaje para notar lo que ocurre, no una etiqueta para poner a nadie. Marcar esta escena registra que exploraste la idea; no evalúa tu forma de hablar ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "¿Sobre el hecho o sobre la persona?",
      body: [
        "Una escena inventada y varias formas de decir lo mismo. Clasifica cada una según de qué habla realmente.",
      ],
      note: "Son frases editoriales, no las tuyas. Ninguna se marca como prohibida: el ejercicio es notar hacia dónde apunta cada una.",
    },
    recall: {
      question: "Según el capítulo, ¿qué distingue una queja de una crítica?",
      options: [
        {
          optionKey: "pqp-c2-opcion-hecho-vs-caracter",
          label:
            "La queja habla de algo concreto que ocurrió; la crítica lo convierte en un rasgo de cómo es la otra persona.",
        },
        {
          optionKey: "pqp-c2-opcion-tono",
          label:
            "La queja se dice con buen tono y la crítica se dice enfadado.",
        },
        {
          optionKey: "pqp-c2-opcion-callar",
          label:
            "La queja es expresar una molestia y la crítica es cualquier molestia que se calla.",
        },
      ],
    },
    summaryScene: {
      title: "Nombrar el hecho deja algo que hacer",
      body: [
        "La distinción no es de cortesía: una queja concreta abre una acción posible, y una crítica al carácter deja poco más que defenderse.",
        "Son patrones, no sentencias. Reconocerlos sirve para elegir de otra manera, no para dictaminar cómo terminará una relación.",
      ],
    },
  },
  {
    slug: "lo-pequeno-es-grande",
    practiceSlug: "una-invitacion-y-tres-respuestas",
    title: "Lo pequeño es grande",
    summary:
      "Buena parte de lo que sostiene un vínculo no ocurre en las conversaciones importantes, sino en intercambios de tres segundos que casi nadie registra.",
    duration: "8–10 minutos",
    intro: {
      title: "Lo pequeño es grande",
      body: [
        "Buena parte de lo que sostiene un vínculo no ocurre en las conversaciones importantes, sino en intercambios de tres segundos que casi nadie registra.",
      ],
      note: "Trabajaremos con una escena inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Principio 3: Acercarse en lugar de alejarse",
      body: "Lee la sección sobre las pequeñas invitaciones que dos personas se lanzan a lo largo del día, y qué ocurre cuando se responden o se dejan pasar.",
    },
    concept: {
      title: "Invitaciones que duran tres segundos",
      body: [
        "Un comentario sobre algo que se vio, una pregunta suelta, un roce al pasar: el capítulo los describe como pequeñas invitaciones a conectar. Casi nunca vienen anunciadas como tales.",
        "Responderlas o dejarlas pasar es una decisión diaria y repetida. No decide nada por sí sola; es su acumulación la que va dando forma al clima entre dos personas.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa cuántas invitaciones respondes ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "Una invitación, tres respuestas",
      body: [
        "La misma invitación breve en dos situaciones distintas. Observa qué podría cambiar en lo que la otra persona alcanza a entender.",
      ],
      note: "Es un caso editorial. Nada se marca como correcto o incorrecto: el ejercicio es notar que la misma respuesta no significa lo mismo en cualquier momento.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué papel tienen las pequeñas invitaciones a conectar?",
      options: [
        {
          optionKey: "pqp-c2-opcion-acumulacion",
          label:
            "Son intercambios breves y frecuentes cuya acumulación va dando forma al clima entre dos personas.",
        },
        {
          optionKey: "pqp-c2-opcion-detalle-menor",
          label:
            "Son detalles agradables, pero lo que de verdad sostiene una relación son las conversaciones importantes.",
        },
        {
          optionKey: "pqp-c2-opcion-cada-una-decide",
          label:
            "Cada invitación no respondida marca un daño difícil de reparar.",
        },
      ],
    },
    summaryScene: {
      title: "La suma, no el gesto",
      body: [
        "Ninguna invitación aislada decide nada. Lo que el capítulo sitúa en el centro es la acumulación: muchas respuestas pequeñas, repetidas.",
      ],
    },
  },
  {
    slug: "aceptar-influencia",
    practiceSlug: "una-decision-tomada-entre-dos",
    title: "Aceptar influencia no es ceder",
    summary:
      "Dejar que la opinión de alguien cambie la tuya suele confundirse con perder. El capítulo propone leerlo al revés.",
    duration: "8–10 minutos",
    intro: {
      title: "Aceptar influencia no es ceder",
      body: [
        "Dejar que la opinión de alguien cambie la tuya suele confundirse con perder. El capítulo propone leerlo al revés.",
      ],
      note: "Trabajaremos con una decisión inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Principio 4: Aceptar la influencia de tu pareja",
      body: "Lee la sección sobre compartir el poder de decidir, y fíjate en la distinción entre aceptar influencia y renunciar a lo propio.",
    },
    concept: {
      title: "Dejarse afectar, sin desaparecer",
      body: [
        "Aceptar influencia es permitir que lo que el otro piensa cuente de verdad en una decisión. No es ceder siempre, y no es dejar de tener criterio: es que la decisión final pueda cambiar de forma porque hubo dos personas pensándola.",
        "Esto describe una relación entre dos personas que pueden decir que no. Cuando alguien no puede negarse sin temer las consecuencias, lo que está ocurriendo no es un problema de influencia y no se arregla cediendo más terreno.",
      ],
      note: "Esa última distinción es importante: esta guía no propone ceder ante presión, control o miedo. Marcar la escena registra que exploraste la idea; no evalúa cómo deciden ustedes.",
    },
    practice: {
      title: "Una decisión tomada entre dos",
      body: [
        "Ordena los pasos de una decisión inventada y fíjate en dónde entra realmente la opinión del otro.",
      ],
      note: "Es un caso editorial, no una decisión tuya.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué significa aceptar la influencia de la otra persona?",
      options: [
        {
          optionKey: "pqp-c2-opcion-cuenta-de-verdad",
          label:
            "Que lo que la otra persona piensa cuente de verdad en la decisión, de modo que pueda cambiar de forma.",
        },
        {
          optionKey: "pqp-c2-opcion-ceder-siempre",
          label:
            "Ceder en la mayoría de las decisiones para evitar el desgaste de discutir.",
        },
        {
          optionKey: "pqp-c2-opcion-turnarse",
          label:
            "Turnarse: cada uno decide sin discusión en las áreas que le corresponden.",
        },
      ],
    },
    summaryScene: {
      title: "Dos criterios, una decisión",
      body: [
        "Aceptar influencia describe una decisión que pudo cambiar de forma porque la pensaron dos, no una en la que uno de los dos deja de opinar.",
        "Y solo describe eso cuando ambos pueden decir que no.",
      ],
    },
  },
  {
    slug: "desacuerdos-perpetuos",
    practiceSlug: "resoluble-o-recurrente",
    title: "Desacuerdos que no se resuelven",
    summary:
      "Hay discusiones que vuelven una y otra vez con el mismo argumento. El capítulo propone que muchas de ellas no están esperando una solución.",
    duration: "8–10 minutos",
    intro: {
      title: "Desacuerdos que no se resuelven",
      body: [
        "Hay discusiones que vuelven una y otra vez con el mismo argumento. El capítulo propone que muchas de ellas no están esperando una solución.",
      ],
      note: "Trabajaremos con desacuerdos inventados para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Principio 5: Resolver los conflictos de manera efectiva",
      body: "Lee la sección sobre los desacuerdos que reaparecen, y fíjate en qué propone el capítulo como objetivo en lugar de resolverlos.",
    },
    concept: {
      title: "Manejar, no cerrar",
      body: [
        "Algunos desacuerdos vienen de diferencias estables entre dos personas —de temperamento, de historia, de lo que cada uno necesita— y por eso reaparecen. El capítulo sostiene que buena parte de los desacuerdos de pareja son de este tipo.",
        "Que reaparezca no significa que algo vaya mal. Cambia el objetivo: en vez de cerrarlo de una vez, se trata de poder hablarlo sin que cada conversación empiece de cero.",
      ],
      note: "«Buena parte» es todo lo que esta guía afirma: el capítulo cita una proporción, y una cifra de población no describe a ninguna pareja en particular. Marcar la escena registra que exploraste la idea.",
    },
    practice: {
      title: "¿Resoluble o recurrente?",
      body: [
        "Varios desacuerdos inventados. Distingue cuáles admiten una solución concreta y cuáles vienen de una diferencia estable que probablemente vuelva.",
      ],
      note: "Son casos editoriales. La clasificación no juzga a nadie: describe qué tipo de conversación pide cada uno.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué conviene hacer con un desacuerdo que reaparece una y otra vez?",
      options: [
        {
          optionKey: "pqp-c2-opcion-poder-hablarlo",
          label:
            "Cambiar el objetivo: en vez de cerrarlo, poder hablarlo sin empezar de cero cada vez.",
        },
        {
          optionKey: "pqp-c2-opcion-insistir",
          label:
            "Insistir hasta encontrar la solución definitiva que todavía no han visto.",
        },
        {
          optionKey: "pqp-c2-opcion-evitarlo",
          label: "Dejar de sacarlo, porque hablarlo solo reabre el malestar.",
        },
      ],
    },
    summaryScene: {
      title: "Que vuelva no significa que falle",
      body: [
        "Un desacuerdo recurrente no es señal de fracaso: cambia el objetivo de la conversación, de cerrarla a poder sostenerla.",
      ],
    },
  },
  {
    slug: "sueno-detras-del-desacuerdo",
    practiceSlug: "lo-que-hay-debajo",
    title: "El sueño detrás del desacuerdo",
    summary:
      "Cuando una discusión se atasca durante años, el capítulo sugiere que el tema del que se habla rara vez es el tema.",
    duration: "8–10 minutos",
    intro: {
      title: "El sueño detrás del desacuerdo",
      body: [
        "Cuando una discusión se atasca durante años, el capítulo sugiere que el tema del que se habla rara vez es el tema.",
      ],
      note: "Trabajaremos con un caso inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "Principio 6: Superar los obstáculos",
      body: "Lee la sección sobre los desacuerdos que se enquistan, y fíjate en qué aparece cuando se mira debajo del problema aparente.",
    },
    concept: {
      title: "Debajo de la postura, algo que importa",
      body: [
        "Detrás de una posición sostenida con fuerza suele haber algo que la persona valora y que no siempre ha dicho en voz alta: una necesidad, una historia, algo que quiere para su vida.",
        "Nombrar eso no resuelve el desacuerdo, y el capítulo no promete que lo haga. Cambia de qué se está hablando, que suele ser la condición para poder avanzar.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no interpreta tus desacuerdos ni te atribuye ningún motivo oculto.",
    },
    practice: {
      title: "Lo que hay debajo",
      body: [
        "Ordena los pasos de un caso inventado, desde la discusión repetida hasta lo que aparece cuando se pregunta por lo que hay detrás.",
      ],
      note: "Es un caso editorial, no tu historia.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué suele haber detrás de un desacuerdo que se enquista durante años?",
      options: [
        {
          optionKey: "pqp-c2-opcion-algo-que-importa",
          label:
            "Algo que cada persona valora y no siempre ha dicho en voz alta: una necesidad o algo que quiere para su vida.",
        },
        {
          optionKey: "pqp-c2-opcion-falta-de-tecnica",
          label:
            "Falta de técnica para negociar: con el método adecuado se resolvería.",
        },
        {
          optionKey: "pqp-c2-opcion-incompatibilidad",
          label:
            "Una incompatibilidad de fondo que indica que la relación no encaja.",
        },
      ],
    },
    summaryScene: {
      title: "Cambiar la pregunta",
      body: [
        "Preguntar qué hay debajo de una postura no cierra el desacuerdo; cambia la conversación, y eso suele ser lo que estaba bloqueado.",
      ],
    },
  },
];

export const PQP_C02_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C02_MICROGUIDES.map((m) => microguidePresentation(PQP_C02, m));

export const PQP_C02_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C02_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C02, m));
