/**
 * PQP-C05's 4 microguides, as the browser needs them.
 *
 * GENERATED by `scripts/pqp/build-web-bundle.mjs --chapter=C05` from
 * `scripts/pqp/chapters/c05.mjs`, which is also what the manifests are
 * built from. Editing this file by hand would let the bundle drift from the
 * manifests the DRAFTs were created from; edit the chapter module and
 * regenerate.
 *
 * This is the PUBLIC half. The three recall labels are here so a reader can
 * choose between them; which one is correct is not, and is not derivable from
 * anything in this file — it lives only in the server-side exercise catalog.
 *
 * The extra scenes each Experience has live in the stored definition and are
 * drawn by the player from there. A guide has three obligatory steps, and the
 * optional scenes are optional by design: listing them here would turn an
 * invitation into a requirement for finishing.
 */

import type { GuidePresentation } from "./guide-presentation";
import type { GuideReaderCopy } from "./guide-reader-copy";
import {
  microguidePresentation,
  microguideReaderCopy,
  type MicroguideChapter,
  type MicroguideEntry,
} from "./guide-microguide-bundle";

const PQP_C05: MicroguideChapter = {
  // The EDITORIAL chapter number, matching the guide keys. Its PLATFORM order
  // is 6 — unit 1 is the front matter.
  keyPrefix: "pqp-c5",
  chapterLabel: "capítulo 5",
};

export const PQP_C05_MICROGUIDES: readonly MicroguideEntry[] = [
  {
    slug: "conflicto-no-es-control",
    practiceSlug: "desacuerdo-o-senales-de-control",
    title: "Un desacuerdo no es una dinámica de control",
    summary:
      "El capítulo abre su lista de causas de conflicto con el poder y el dominio. Esta guía se detiene ahí, porque no todo lo que parece una discusión lo es.",
    duration: "8–10 minutos",
    intro: {
      title: "Un desacuerdo no es una dinámica de control",
      body: [
        "El capítulo abre su lista de causas de conflicto con el poder y el dominio. Esta guía se detiene ahí, porque no todo lo que parece una discusión lo es.",
      ],
      note: "Trabajaremos solo con escenas inventadas. No se te pedirá describir tu situación, y nada de lo que pienses aquí se guarda. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "1. Poder y dominio",
      body: "Lee la sección donde el capítulo describe lo que ocurre cuando uno de los dos busca imponer, y fíjate en cómo lo distingue de una diferencia de criterio.",
    },
    concept: {
      title: "Quién puede decir que no",
      body: [
        "En un desacuerdo, las dos personas pueden sostener su postura, negarse y seguir estando. La conversación puede ser incómoda y aun así ninguna de las dos pierde nada por opinar.",
        "Hay situaciones distintas: cuando una persona no puede negarse, opinar o decidir sin que haya consecuencias —enfado sostenido, castigo, vigilancia, aislamiento, miedo—, lo que está ocurriendo no es un desacuerdo mal llevado. Es otra cosa, y tiene otro nombre.",
        "La diferencia importa por lo práctico: las herramientas de este capítulo —elegir el momento, hablar en presente, buscar acuerdos— sirven para desacuerdos. No sirven para el control, y aplicarlas ahí puede dejar a alguien intentando negociar algo que no se negocia.",
      ],
      note: "Si algo de esto se parece a tu situación, lo que corresponde no es una técnica de conversación sino apoyo: alguien de confianza, un profesional o un servicio especializado de tu país. Esta guía no evalúa tu relación ni saca conclusiones sobre ella.",
    },
    practice: {
      title: "¿Desacuerdo o señales de control?",
      body: [
        "Cuatro escenas inventadas. Distingue las que describen una diferencia entre dos personas de las que muestran señales de control.",
      ],
      note: "Son escenas editoriales, nunca tu relación, y el ejercicio clasifica situaciones, no personas. Reconocer señales de control en una escena no dice nada sobre nadie que conozcas.",
    },
    recall: {
      question:
        "Según la idea trabajada en esta guía, ¿qué distingue un desacuerdo de una dinámica de control?",
      options: [
        {
          optionKey: "pqp-c5-opcion-quien-puede-negarse",
          label:
            "Que en un desacuerdo las dos personas pueden sostener su postura y negarse; en una dinámica de control, una no puede hacerlo sin consecuencias.",
        },
        {
          optionKey: "pqp-c5-opcion-intensidad",
          label:
            "Que las discusiones son más intensas y frecuentes cuando hay control.",
        },
        {
          optionKey: "pqp-c5-opcion-tema",
          label:
            "Que el control aparece siempre en temas de dinero o de familia, y el desacuerdo en temas cotidianos.",
        },
      ],
    },
    summaryScene: {
      title: "Dos cosas distintas, dos respuestas distintas",
      body: [
        "Un desacuerdo se trabaja conversando. Una dinámica de control no se resuelve conversando mejor, y proponerlo así puede dejar a alguien sola con el problema.",
        "Distinguirlas es lo que esta guía enseña. Para lo segundo, lo que ayuda es apoyo.",
      ],
    },
  },
  {
    slug: "una-cosa-a-la-vez",
    practiceSlug: "hoy-o-el-historial",
    title: "Una cosa a la vez",
    summary:
      "Una conversación sobre algo de esta mañana puede acabar siendo sobre los últimos cinco años. El capítulo explica qué se pierde por el camino.",
    duration: "8–10 minutos",
    intro: {
      title: "Una cosa a la vez",
      body: [
        "Una conversación sobre algo de esta mañana puede acabar siendo sobre los últimos cinco años. El capítulo explica qué se pierde por el camino.",
      ],
      note: "Trabajaremos con frases inventadas para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "4. Enfócate en el presente",
      body: "Lee la sección sobre quedarse en lo que ocurrió hoy, y fíjate en qué nombra el capítulo como la tentación.",
    },
    concept: {
      title: "El historial satura la conversación",
      body: [
        "Traer episodios anteriores puede sentirse como aportar contexto, pero suele hacer lo contrario: multiplica los temas abiertos y deja el de hoy sin tratar.",
        "No significa que el pasado no importe. Significa que una conversación puede sostener un asunto a la vez, y que elegir cuál se está tratando es parte de que llegue a alguna parte.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa cómo discutes ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "¿Hoy o el historial?",
      body: [
        "Varias formas inventadas de abrir la misma conversación. Distingue las que se quedan en lo de hoy de las que abren el archivo.",
      ],
      note: "Son frases editoriales, no las tuyas. Ninguna está prohibida: el ejercicio es notar cuántos temas abre cada una.",
    },
    recall: {
      question:
        "Según el capítulo, ¿qué ocurre al traer discusiones pasadas a una conversación sobre algo de hoy?",
      options: [
        {
          optionKey: "pqp-c5-opcion-satura",
          label:
            "Que la conversación se satura y se vuelve más difícil resolver lo que se quería tratar.",
        },
        {
          optionKey: "pqp-c5-opcion-contexto",
          label:
            "Que aporta el contexto necesario para que el otro entienda la magnitud del problema.",
        },
        {
          optionKey: "pqp-c5-opcion-igual",
          label:
            "Que da igual: lo que decide el resultado es el tono con que se diga.",
        },
      ],
    },
    summaryScene: {
      title: "Un asunto por conversación",
      body: [
        "Una conversación sostiene un tema a la vez. Elegir cuál es no borra el resto: los deja para su momento.",
      ],
    },
  },
  {
    slug: "el-momento-importa",
    practiceSlug: "cuando-abrir-la-conversacion",
    title: "El momento importa",
    summary:
      "La misma frase, dicha en dos momentos distintos, puede abrir una conversación o una discusión. El capítulo se detiene en eso.",
    duration: "8–10 minutos",
    intro: {
      title: "El momento importa",
      body: [
        "La misma frase, dicha en dos momentos distintos, puede abrir una conversación o una discusión. El capítulo se detiene en eso.",
      ],
      note: "Trabajaremos con una escena inventada para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "9. Elige bien el momento",
      body: "Lee la sección sobre cuándo plantear un tema, y fíjate en qué dice el capítulo que agrava muchas discusiones.",
    },
    concept: {
      title: "Elegir cuándo también es parte",
      body: [
        "El capítulo señala que muchas conversaciones se tuercen no por lo que se dice sino por cuándo se dice: al llegar agotados, delante de otras personas, en mitad de otra cosa.",
        "Elegir el momento no es evitar el tema. Es lo contrario: es darle una oportunidad razonable de que se pueda hablar.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa cuándo hablas ni infiere nada sobre tu relación.",
    },
    practice: {
      title: "Cuándo abrir la conversación",
      body: [
        "El mismo tema planteado en dos momentos distintos. Observa qué cambia en lo que puede ocurrir después.",
      ],
      note: "Es un caso editorial. Nada se marca como correcto: no existe un momento perfecto.",
    },
    recall: {
      question:
        "Según el capítulo, ¿por qué muchas discusiones se agravan sin que el tema haya cambiado?",
      options: [
        {
          optionKey: "pqp-c5-opcion-mal-momento",
          label:
            "Porque se abren en un momento o un lugar en que ninguno de los dos puede sostener la conversación.",
        },
        {
          optionKey: "pqp-c5-opcion-postergar",
          label:
            "Porque conviene aplazar los temas difíciles hasta que dejen de doler.",
        },
        {
          optionKey: "pqp-c5-opcion-caracter",
          label:
            "Porque hay personas que no están hechas para hablar de temas difíciles.",
        },
      ],
    },
    summaryScene: {
      title: "Cuándo, no solo qué",
      body: [
        "Elegir el momento no aplaza la conversación: le da una oportunidad de ocurrir.",
      ],
    },
  },
  {
    slug: "acuerdo-no-es-victoria",
    practiceSlug: "de-la-postura-al-acuerdo",
    title: "Un acuerdo no es una victoria",
    summary:
      "Terminar una discusión y resolver un conflicto no son lo mismo. El capítulo cierra sus claves por ahí.",
    duration: "8–10 minutos",
    intro: {
      title: "Un acuerdo no es una victoria",
      body: [
        "Terminar una discusión y resolver un conflicto no son lo mismo. El capítulo cierra sus claves por ahí.",
      ],
      note: "Trabajaremos con un caso inventado para el ejercicio. Puedes salir y volver cuando quieras. Nada de lo que escribas sale de tu dispositivo.",
    },
    passage: {
      title: "10. Lleguen a acuerdos",
      body: "Lee la sección final de las claves, y fíjate en cómo describe el capítulo un conflicto resuelto.",
    },
    concept: {
      title: "Concreto, y sostenible por los dos",
      body: [
        "Un acuerdo, tal como lo describe el capítulo, no es que alguien acepte la postura del otro: es algo concreto que las dos personas pueden sostener.",
        "Eso lo hace comprobable. Un acuerdo que nadie sabría decir si se cumplió no era un acuerdo, era el final de una discusión.",
      ],
      note: "Marcar esta escena registra que exploraste la idea; no evalúa vuestros acuerdos.",
    },
    practice: {
      title: "De la postura al acuerdo",
      body: [
        "Ordena los pasos de un caso inventado, desde dos posturas enfrentadas hasta algo que ambos pueden sostener.",
      ],
      note: "Es un caso editorial, no tu historia.",
    },
    recall: {
      question:
        "Según el capítulo, ¿cuándo se considera resuelto un conflicto de pareja?",
      options: [
        {
          optionKey: "pqp-c5-opcion-acuerdo-concreto",
          label:
            "Cuando llegan a un acuerdo concreto que ambos pueden sostener, no cuando uno gana.",
        },
        {
          optionKey: "pqp-c5-opcion-convencer",
          label:
            "Cuando uno de los dos logra explicar su postura lo bastante bien como para convencer al otro.",
        },
        {
          optionKey: "pqp-c5-opcion-dejar-pasar",
          label:
            "Cuando el malestar se disipa solo y el tema deja de aparecer.",
        },
      ],
    },
    summaryScene: {
      title: "Comprobable, no ganado",
      body: [
        "Un acuerdo se reconoce en que ambos pueden sostenerlo y en que se sabría decir si se cumplió.",
      ],
    },
  },
];

export const PQP_C05_PRESENTATIONS: readonly GuidePresentation[] =
  PQP_C05_MICROGUIDES.map((m) => microguidePresentation(PQP_C05, m));

export const PQP_C05_READER_COPY: readonly GuideReaderCopy[] =
  PQP_C05_MICROGUIDES.map((m) => microguideReaderCopy(PQP_C05, m));
